version: '3.7'

services:

  postgres1:
    image: postgres:11.1
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./databases/postgres1:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - MySites_network

  web:
    build: ./web
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
    depends_on:
      - postgres1
    command: gunicorn -c gunicorn.conf MySites.wsgi
    volumes:
      - ./web/MySites:/MySites
    ports:
      - "8000:8000"
    networks:
      - MySites_network

  nginx:
    build: ./nginx
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/MySites/static:/var/www/static
      - ./web/MySites/media:/var/www/media
    networks:
      - MySites_network

networks:
  MySites_network:
    driver: bridge